version: '2'

services:
  web:
    container_name: lumen_app-nginx
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html/
      - ./envConfig/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      lumen_app_net:
        ipv4_address: 172.28.0.2
  php:
    container_name: lumen_app-fpm
    image: php:7.3-fpm-alpine
    volumes:
      - .:/var/www/html/
      - ./envConfig/php.ini:/usr/local/etc/php/php.ini
    networks:
      lumen_app_net:
        ipv4_address: 172.28.0.4
  mysql:
    container_name: lumen_app-mysql
    image: mysql:5.7
    ports:
      - "3306"
    volumes:
      - mysqldata2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen_app_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      lumen_app_net:
        ipv4_address: 172.28.0.6

networks:
  lumen_app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  mysqldata2:
    driver: local